### ISSUE TITLE
[Bug] Highlight default background

### ISSUE THREAD

**Issue by vuzzer** [AppFlowy-IO/appflowy-editor#127] opened 2023-05-20 11:45 UTC
### Bug Description

If I highlight in purple, there is no way to go back plain

### How to Reproduce

Highlight text in purple

### Expected Behavior

There should be an option for me to undo highlight in any color

### Operating System

Macos

### AppFlowy Editor Version(s)

Main branch

### Screenshots

No response

### Additional Context

No response

**Comment by vuzzer** [comment] 2023-05-20 11:51
I work on this issue to fix #2451 from [AppFlowy](https://github.com/AppFlowy-IO/AppFlowy/issues/2451)

**Comment by MayurSMahajan** [comment] 2023-05-21 11:35
Hey @vuzzer! Hope you are doing great. You did not need to create a duplicate of the AppFlowy issue here, you can close this issue.

**Comment by MayurSMahajan** [comment] 2023-05-22 16:55
Yes, you can close this issue, and work on the issue, when you submit a PR in appflowy-editor, you can still add a link to the original issue in the Appflowy repository. Thank you for contributing!

**Closed** 2023-05-22 18:21 UTC
